vaiii

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -41,6 +41,27 @@ jobs:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Upload docker-compose.yml to EC2
+        uses: appleboy/scp-action@master
+        with:
+          host: ${{ env.INSTANCE_IP }}
+          username: ec2-user
+          key: ${{ env.PRIVATE_KEY }}
+          source: "python-fast-app/docker-compose.yml"  # Send the latest docker-compose.yml
+          target: "/home/ec2-user/python-fast-app/"  # Destination on EC2
+
+      - name: Upload other necessary files to EC2
+        uses: appleboy/scp-action@master
+        with:
+          host: ${{ env.INSTANCE_IP }}
+          username: ec2-user
+          key: ${{ env.PRIVATE_KEY }}
+          source: "./python-fast-app*"  # Send all necessary files (like main.py, requirements.txt, etc.)
+          target: "/home/ec2-user/python-fast-app/"  # Destination on EC2
+
       - name: SSH into EC2 and Deploy
         uses: appleboy/ssh-action@master
         with:
@@ -48,28 +69,8 @@ jobs:
           username: ec2-user
           key: ${{ env.PRIVATE_KEY }}
           script: |
-            # Ensure the directory exists
-            if [ ! -d "/home/ec2-user/python-fast-app" ]; then
-              mkdir -p /home/ec2-user/python-fast-app
-            fi
-
-            # Navigate to the directory where docker-compose.yml is located
             cd /home/ec2-user/python-fast-app
-
-            # Check if docker-compose.yml is present
-            ls -la
-
-            # Pull the latest image (not necessary if already pulled)
-            sudo docker pull riyad2003/python-fast-app:v1
-
-            # Stop any running containers
-            sudo docker-compose down || true
-
-            # Pull the latest images as per docker-compose.yml
-            sudo docker-compose pull
-
-            # Start the containers in detached mode
-            sudo docker-compose up -d
-
-            # Clean up old Docker images
-            sudo docker image prune -f
+            sudo docker-compose down || true  # Stop running containers
+            sudo docker-compose pull  # Pull latest images from Docker Hub
+            sudo docker-compose up -d  # Start services
+            sudo docker image prune -f  # Clean up old images
